Repository carpentries-incubator/SDC-BIDS-dMRI, pull requests merged in 2021-03, with the labels that each got.

#69 ENH: Add different orientations to CSD Episode
  _episodes/constrained_spherical_deconvolution.md
  code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
  fig/constrained_spherical_deconvolution/csd_odfs.png
  fig/constrained_spherical_deconvolution/csd_peaks.png
  fig/constrained_spherical_deconvolution/csd_peaks_fodfs.png
  fig/constrained_spherical_deconvolution/frf.png
Labels: type:enhancement

#70 DOC: Fix typo in citation author name
  _episodes/diffusion_tensor_imaging.md
Labels: type:typo text

#75 BUG: Mark output cell as Markdown in CSD episode
  code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Labels: type:bug

#74 DOC: Declare no reported problems in instructor notes
  _extras/guide.md
Labels: type:instructor guide

#71 STYLE: Prefer `{{ relative_root_path }}` to resolve figure paths
  _episodes/constrained_spherical_deconvolution.md
  _episodes/diffusion_tensor_imaging.md
  _episodes/introduction.md
  _episodes/local_tractography.md
  _episodes/preprocessing.md
  _episodes/probabilistic_tractography.md
Labels: type:template and tools

#76 ENH: Put the `fury` camera setup into a function
  _episodes/constrained_spherical_deconvolution.md
  code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Labels: type:enhancement

#77 DOC: Add discussion section about camera setup
  _extras/discuss.md
Labels: type:discussion

#80 DOC: Improve the completeness of tractography method list
  _episodes/tractography.md
Labels: type:enhancement

#79 DOC: Add further aspects of dMRI to discussion
  _extras/discuss.md
Labels: type:discussion

#87 BUG: Add missing base path include
  _extras/discuss.md
Labels: type:bug

#89 STYLE: Change tabs to whitespaces
  _episodes/probabilistic_tractography.md
  code/probabilistic_tractography/probabilistic_tractography.ipynb
Labels: type:formatting

#91 BUG: Use the right bvec file in prob tractography episode
  _episodes/probabilistic_tractography.md
  code/probabilistic_tractography/probabilistic_tractography.ipynb
Labels: type:bug

#90 BUG: Fix probabilistic tractography notebook
  code/probabilistic_tractography/probabilistic_tractography.ipynb
Labels: type:bug

#94 BUG: Fix deterministic tractography notebook
  code/deterministic_tractography/deterministic_tractography.ipynb
  code/deterministic_tractography/solutions/deterministic_tractography_solutions.ipynb
Labels: type:bug

#95 STYLE: Comply with PEP 8
  _episodes/probabilistic_tractography.md
  code/probabilistic_tractography/probabilistic_tractography.ipynb
Labels: type:formatting

#97 ENH: Add coronal and sagittal views to GFA plot
  _episodes/probabilistic_tractography.md
  code/probabilistic_tractography/probabilistic_tractography.ipynb
  fig/probabilistic_tractography/gfa.png
Labels: type:enhancement

#96 ENH: Fix GitHub actions notebook test workflow
  .github/workflows/build-test.yaml
Labels: type:enhancement

#98 ENH: Constrain the slices to be shown to three dimensions
  _episodes/constrained_spherical_deconvolution.md
  code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Labels: type:enhancement

#107 ENH: Define the SH order at a single location
  _episodes/probabilistic_tractography.md
  code/probabilistic_tractography/probabilistic_tractography.ipynb
Labels: type:enhancement

#113 ENH: Change SH order in probabilistic tractography notebook
  code/probabilistic_tractography/probabilistic_tractography.ipynb
Labels: type:enhancement

#114 ENH: Save and show the probabilistic tracking episode peaks
  _episodes/probabilistic_tractography.md
  code/probabilistic_tractography/probabilistic_tractography.ipynb
  fig/probabilistic_tractography/peaks.png
Labels: type:enhancement

#111 ENH: Remove Travis CI config file
  .travis.yml
Labels: type:template and tools
