Repository carpentries-incubator/SDC-BIDS-dMRI, pull requests merged in 2021-08, with the labels that each got.

#174 BUG: Fix `DIPY` fiber response function method call parameter
  code/probabilistic_tractography/probabilistic_tractography.ipynb
Labels: type:bug

#172 ENH: Run GitHub actions build test workflow on PRs
  .github/workflows/build-test.yaml
Labels: type:enhancement

#176 BUG: Fix data paths in preprocessing episode solutions notebook
  code/preprocessing/solutions/preprocessing_solutions.ipynb
Labels: type:bug

#180 BUG: Fix data paths in preprocessing episode solutions notebook
  code/preprocessing/solutions/preprocessing_solutions.ipynb
Labels: type:bug

#175 ENH: Install FSL and ANTs within GitHub Actions
  .github/workflows/build-test.yaml
Labels: type:enhancement, dependencies

#186 STYLE: Remove unused imports
  _episodes/diffusion_tensor_imaging.md
  _episodes/probabilistic_tractography.md
  code/diffusion_tensor_imaging.ipynb
  code/probabilistic_tractography.ipynb
Labels: type:enhancement

#187 ENH: Allow initial dot for BIDS extension entity
  _episodes/preprocessing.md
  code/preprocessing.ipynb
Labels: type:enhancement

#189 STYLE: Remove trailing whitespaces
  code/diffusion_tensor_imaging.ipynb
  code/preprocessing.ipynb
  code/probabilistic_tractography.ipynb
Labels: type:enhancement

#191 ENH: Add AD and RD map figures to DTI episode
  _episodes/diffusion_tensor_imaging.md
  fig/diffusion_tensor_imaging/axial_diffusivity_map.png
  fig/diffusion_tensor_imaging/radial_diffusivity_map.png
Labels: type:enhancement

#188 STYLE: Move imports closer to used location in prob tractogr episode
  _episodes/probabilistic_tractography.md
  code/probabilistic_tractography.ipynb
Labels: type:enhancement
