Repository carpentries-incubator/SDC-BIDS-dMRI, pull requests merged in 2021-04, with the labels that each got.

#92 ENH: Reuse the anatomical orientation views generating method
  _episodes/constrained_spherical_deconvolution.md
  _episodes/deterministic_tractography.md
  _episodes/probabilistic_tractography.md
  _extras/discuss.md
  code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
  code/deterministic_tractography/deterministic_tractography.ipynb
  code/probabilistic_tractography/probabilistic_tractography.ipynb
  utils/__init__.py
  utils/visualization_utils.py
Labels: type:enhancement

#112 ENH: Bring 404 page from lesson example
  404.md
Labels: type:template and tools

#119 STYLE: Remove excessive whitespace around RGB FA map plot
  fig/diffusion_tensor_imaging/plot_fa_rgb.png
Labels: type:formatting

#122 BUG: Fix the anatomical slice figure sorting
  utils/visualization_utils.py
Labels: type:bug

#124 ENH: Remove empty cell from CSD notebook
  code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Labels: type:formatting

#123 STYLE: Mark numeric cell as Markdown in CSD episode
  code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
Labels: type:formatting

#125 ENH: Call NiBabel `get_fdata()` instead of `get_data()`
  _episodes/deterministic_tractography.md
  _episodes/diffusion_tensor_imaging.md
  code/deterministic_tractography/deterministic_tractography.ipynb
  code/diffusion_tensor_imaging/diffusion_tensor_imaging.ipynb
  code/diffusion_tensor_imaging/solutions/diffusion_tensor_imaging_solutions.ipynb
Labels: type:enhancement

#128 BUG: Fix call to visualization helper and skip fury visualizations in tests
  _episodes/constrained_spherical_deconvolution.md
  _episodes/deterministic_tractography.md
  _episodes/probabilistic_tractography.md
  code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
  code/deterministic_tractography/deterministic_tractography.ipynb
  code/probabilistic_tractography/probabilistic_tractography.ipynb
Labels: type:bug

#116 FIX: Update and sync DTI episode
  _episodes/diffusion_tensor_imaging.md
  code/diffusion_tensor_imaging/diffusion_tensor_imaging.ipynb
  code/diffusion_tensor_imaging/solutions/diffusion_tensor_imaging_solutions.ipynb
Labels: status:in progress, type:bug

#134 ENH: Update probabilistic tractography notebook
  code/probabilistic_tractography/probabilistic_tractography.ipynb
  fig/probabilistic_tractography/peaks.png
  fig/probabilistic_tractography/tractogram_probabilistic_dg_pmf.png
  fig/probabilistic_tractography/tractogram_probabilistic_dg_sh.png
  fig/probabilistic_tractography/tractogram_probabilistic_dg_sh_pmf.png
Labels: type:enhancement

#135 FIX: Actions workflow - rm zip
  .github/workflows/build-test.yaml
Labels: type:bug

#120 ENH: Update deterministic tractography
  .github/workflows/build-test.yaml
  _episodes/deterministic_tractography.md
  code/deterministic_tractography/deterministic_tractography.ipynb
  code/deterministic_tractography/solutions/deterministic_tractography_solutions.ipynb
  fig/deterministic_tractography/tractogram_deterministic_EuDX.png
  fig/deterministic_tractography/tractogram_deterministic_ex1.png
  fig/deterministic_tractography/tractogram_deterministic_fa.png
Labels: status:in progress, type:enhancement

#137 FIX: Reset notebook kernel
  code/deterministic_tractography/solutions/deterministic_tractography_solutions.ipynb
Labels: type:bug

#117 ENH: Add csd exercise
  .github/workflows/build-test.yaml
  _episodes/constrained_spherical_deconvolution.md
  code/constrained_spherical_deconvolution/constrained_spherical_deconvolution.ipynb
  code/constrained_spherical_deconvolution/solutions/constrained_spherical_deconvolution_solutions.ipynb
  fig/constrained_spherical_deconvolution/odf_multiple_angles.png
Labels: type:enhancement

#139 FIX: add skip tag for utils
  _episodes/deterministic_tractography.md
  code/deterministic_tractography/solutions/deterministic_tractography_solutions.ipynb
Labels: type:bug

#142 ENH: Split apart visualization cell in CSD exercise
  _episodes/constrained_spherical_deconvolution.md
  code/constrained_spherical_deconvolution/solutions/constrained_spherical_deconvolution_solutions.ipynb
Labels: type:enhancement

#146 STYLE: Fix unknown code block warning
  setup.md
Labels: type:formatting

#145 STYLE: Use a separate, lesson-specific links file
  _includes/lesson_links.md
  _includes/links.md
Labels: type:template and tools

#144 ENH: Add website build workflow status badge to `README`
  README.md
Labels: type:formatting, type:template and tools

#148 ENH: Fix cell test skip command
  code/constrained_spherical_deconvolution/solutions/constrained_spherical_deconvolution_solutions.ipynb
Labels: type:enhancement
